version: '3'

services:
  reverse-proxy:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --docker.watch \
      --logLevel=DEBUG \
      --defaultEntryPoints='http,https' \
      --entryPoints='Name:http Address::80' \
      --entryPoints='Name:https Address::443 TLS' \
      --acme \
      --acme.entryPoint='https' \
      --acme.email='yo@cyrale.me' \
      --acme.ondemand=false \
      --acme.acmelogging=true \
      --acme.onhostrule=true \
      --acme.storage='/etc/traefik/acme/acme.json'
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - webgateway-data:/etc/traefik/acme/
    labels:
      - "traefik.backend=reverse-proxy"
      - "traefik.frontend.rule=Host:reverse-proxy.docker.localhost"

networks:
  webgateway:

volumes:
  webgateway-data: